// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beujgzabcqmrojufykud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJldWpnemFiY3Ftcm9qdWZ5a3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjU4ODgsImV4cCI6MjA3MDU0MTg4OH0.szqKntUStBo-poJtzvjF8tENjKyqlSJwmSb7B7eOgW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});